import pandas as pd
from datetime import datetime
from collections import defaultdict

# Read data from CSV file
df = pd.read_csv('orders.csv')

# Task 1: Compute total revenue generated by the online store for each month
df['order_date'] = pd.to_datetime(df['order_date'])
df['month'] = df['order_date'].dt.month
monthly_revenue = df.groupby('month')['product_price'].sum()

# Task 2: Compute total revenue generated by each product
product_revenue = df.groupby('product_id')['product_price'].sum()

# Task 3: Compute total revenue generated by each customer
customer_revenue = df.groupby('customer_id')['product_price'].sum()

# Task 4: Identify the top 10 customers by revenue
top_customers = customer_revenue.nlargest(10)

# Print results
print("Monthly Revenue:")
print(monthly_revenue)
print("\nProduct Revenue:")
print(product_revenue)
print("\nCustomer Revenue:")
print(customer_revenue)
print("\nTop 10 Customers by Revenue:")
print(top_customers)
